version: 0.1
env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
phases:
  install:
    commands:
      - echo installing maven...
      - yum update -y
      - yum install -y maven
  build:
    commands:
      - echo building the xml json converter
      - mvn install
artifacts:
  files:
    - target/*.jar
    - scripts/*.sh
    - buildspec.yml
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'